blog_fragment_caching/config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles
  resources :comments
  # get 'comments/new'

  # get 'aritcles/index'

  # get 'aritcles/show'

  # get 'aritcles/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog_fragment_caching/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_fragment_caching/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments

  def cache_comments_count
    Rails.cache.fetch([self,"comments_count"]){ comments.size}
  end

  def cached_comments
    Rails.cache.fetch([self,"comments"]){comments.to_a}
  end
end

blog_fragment_caching/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, touch: true
end

blog_fragment_caching/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :miniprofiler
  private
    def miniprofiler
      Rack::MiniProfiler.authorize_request
    end
end

blog_fragment_caching/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(article: @article)
    @recent_articles = Article.order("published_at desc")
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      expire_fragment("recent_articles")
      redirect_to @article, notice: "Article has been updated."
    else
      render "edit"
    end
  end
  private
    def article_params
      params.require(:article).permit(:name, :author_name, :content)
    end
end

blog_fragment_caching/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment.article, notice: "Successfully created comment."
    else
      render :new
    end
  end
  private
    def comment_params
      params.require(:comment).permit(:name, :content, :article_id)
    end
end

blog_fragment_caching/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_fragment_caching/app/helpers/comments_helper.rb
module CommentsHelper
end

blog_fragment_caching/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 12, :cols => 35 %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

blog_fragment_caching/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
<% @articles.each do |article| %>
  <h2>
    <%= link_to article.name, article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="info">
    by <%= article.author_name %>
    on <%= article.published_at.strftime('%b %d, %Y') %>
  </div>
  <div class="content"><%= article.content %></div>
<% end %>
</div>

blog_fragment_caching/app/views/articles/show.html.erb
<% cache "recent_articles" do %>
  <div id="recent_articles">
    <h3>Recent Articles</h3>
    <ul>
    <% @recent_articles.each do |article| %>
      <% cache ['v1',article] do %>
        <li><%= link_to article.name, article %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
<% end %>


<div id="article">
  <h1><%= @article.name %></h1>
  <%= @article.content %>
  <p>
    <%= link_to "Edit", edit_article_path %> |
    <%= link_to "Browse Articles", articles_path %>
  </p>

  <h2><%= pluralize(@article.cache_comments_count, "comment") %></h2>
  <div id="comments">
    <%= render @article.cached_comments %>
  </div>
  <%= render "comments/form" %>
</div>

blog_fragment_caching/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogFragmentCaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>