cache_digest/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects
  resources :tasks
  root to: 'projects#index'
end

cache_digest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cache_digest/app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

  def incomplete_tasks
    tasks.where(completed_at: nil)
  end
end

cache_digest/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, touch: true
end

cache_digest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cache_digest/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.findd(params[:id])
    @project.update(project_params)
    redirect_to project_url, notice: "Project was successfully updated"
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to project_url, notice: "Project was successfully destroyed"
    end
  end
  private
    def project_params
      params.require(:project).permit(:name)
    end
end

cache_digest/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def edit
    @task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to project_url, notice: "Task was successfully updated"
  end
  private
    def task_params
      params.require(:task).permit(:name, :completed_at)
    end
end

cache_digest/app/helpers/application_helper.rb
module ApplicationHelper
end

cache_digest/app/helpers/projects_helper.rb
module ProjectsHelper
end

cache_digest/app/helpers/tasks_helper.rb
module TasksHelper
end

cache_digest/app/views/projects/_project.html.erb
<% cache project do %>
  <h2><%= link_to project.name, edit_project_path(project) %></h2>
  <ol><%= render partial: 'tasks/task',collection: project.incomplete_tasks %></ol>
<% end %>

cache_digest/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cache_digest/app/views/projects/index.html.erb
<h1>Projects</h1>

<%= render @projects %>